name=ESP32_VS1053_Stream
version=3.0.4
author=Cellie
maintainer=Cellie
sentence=This is a Arduino IDE library for playing mp3, aac, ogg and flac local files and online streams with a vs1053 decoder.
paragraph=This library plays http, insecure https and chunked streams and parses the stream metadata. Also plays local mp3, ogg and flac files.
category=Other
url=https://github.com/CelliesProjects/ESP32_VS1053_Stream
architectures=esp32
includes=ESP32_VS1053_Stream.h
